apiVersion: apps/v1
kind: Deployment
metadata:
  name: villains-service
  labels:
    app: villains-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: villains-service
  template:
    metadata:
      labels:
        app: villains-service
    spec:
      containers:
      - name: villains-service
        image: chaosmaker/villains-service:latest
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        env:
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: villains-config
                key: database
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: villains-database-secret
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: villains-database-secret
                key: password