apiVersion: apps/v1
kind: Deployment
metadata:
  name: villains-service
  labels:
    app: villains-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: villains-service
  template:
    metadata:
      labels:
        app: villains-service
    spec:
      containers:
      - name: villains-service
        image: chaosmaker/villains-service:1.0.1
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent
        env:
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: villains-config
                key: database
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: villains-database-secret
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: villains-database-secret
                key: password