# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: 🔧 Setup Jaava
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: 3.8.5

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Set Image Tag
      run : echo "BUILD_IMAGE_TAG=${GITHUB_REF_NAME}-${GITHUB_SHA}" >> $GITHUB_ENV
    - name: package and build docker images
      run: |
        mvn -f fight/pom.xml clean install
        docker build -f fight/src/main/docker/Dockerfile.jvm -t chaosmaker/fight-service:${{ env.BUILD_IMAGE_TAG }} fight/
        mvn -f hero/pom.xml clean install
        docker build -f hero/src/main/docker/Dockerfile.jvm -t chaosmaker/hero-service:${{ env.BUILD_IMAGE_TAG }} hero/
        mvn -f villain/pom.xml clean install
        docker build -f villain/src/main/docker/Dockerfile.jvm -t chaosmaker/villain-service:${{ env.BUILD_IMAGE_TAG }} villain/
    - name: Push images to registry
      run: |
        docker push chaosmaker/fight-service:${{ env.BUILD_IMAGE_TAG }}
        docker push chaosmaker/hero-service:${{ env.BUILD_IMAGE_TAG }}
        docker push chaosmaker/villain-service:${{ env.BUILD_IMAGE_TAG }}
    

        
